import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["prompt.hello", { text: "from tRPC" }]);
  const goodbye = trpc.useQuery(["prompt.goodbye"]);
  console.log(goodbye)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
          {goodbye.data ? <p>{JSON.stringify(goodbye.data.farewell)}</p> : <p>Loading..</p>}
      </div>
    </>
  );
};

export default Home;
